// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9EEKIrRTGTb1M0-oIBX67zXdRTXHabbs',
    appId: '1:387090049977:web:26435c7bd4dfd02f3f6468',
    messagingSenderId: '387090049977',
    projectId: 'chat-app-910ff',
    authDomain: 'chat-app-910ff.firebaseapp.com',
    databaseURL: 'https://chat-app-910ff-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-910ff.appspot.com',
    measurementId: 'G-PWTD41KTZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbtOABdMNIkEV2Q_T2LNYEIu9F8N2DBqI',
    appId: '1:387090049977:android:4384436d7b3ea0bd3f6468',
    messagingSenderId: '387090049977',
    projectId: 'chat-app-910ff',
    databaseURL: 'https://chat-app-910ff-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-910ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk9EVsLehcHnP7freQyAilUxBMXQf0bwM',
    appId: '1:387090049977:ios:5d91ad75509faceb3f6468',
    messagingSenderId: '387090049977',
    projectId: 'chat-app-910ff',
    databaseURL: 'https://chat-app-910ff-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-910ff.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk9EVsLehcHnP7freQyAilUxBMXQf0bwM',
    appId: '1:387090049977:ios:b90713cd7c59a1d53f6468',
    messagingSenderId: '387090049977',
    projectId: 'chat-app-910ff',
    databaseURL: 'https://chat-app-910ff-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-910ff.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
